version: "3.8"

networks:
  kafka_net:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_net
    
  kafka0:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka0
    hostname: kafka0
    ports:
      - 9092:9092
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_BROKER_ID:1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:1
      - KAFKA_CREATE_TOPICS:"Topic-Demo:1:1"
    networks:
      - kafka_net
    depends_on:
      - zookeeper
    
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka0
    environment:
      - KAFKA_CLUSTERS_0_NAME:local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS:kafka0:9092
      - KAFKA_CLUSTERS_0_METRICS_PORT:9997
      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY:http://schemaregistry0:8085
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME:first
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS:http://kafka-connect0:8083
      - DYNAMIC_CONFIG_ENABLED:true
  


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local